# Introdução ao Aprendizado de Máquina
Bruno Bogaz Zarpelão <br>
brunozarpelao@uel.br

<i>Etapa 3 (Regressão) - Exercício</i>

O dataset <b>Automóveis</b> contém 205 instancias com 26 atributos:

1. Simbologia </br>              
2. Desavalorização </br>
3. Fabricante </br>
4. Combustível</br>
5. Aspiração</br>
6. Número de portas </br>
7. Estilo </br>
8. Tração </br>
9. Localização do Motor</br>
10. Base da roda </br>
11. Comprimento</br>
12. Largura</br>
13. Altura</br>
14. Peso</br>
15. Tipo do motor</br>
16. Quantidade de Cilindros</br>
17. Tamanho do Motor</br>
18. Sistema de Combustível</br>
19. Calibre do Motor</br>
20. Volume</br>
21. Taxa de Compressão</br>
22. Cavalos</br>
23. Pico de RPM</br>
24. Consumo na cidade</br>
25. Consumo na rodovia</br>
26. Valor</br>

Implementar as seguintes tarefas para este conjunto de dados:

a) Utilizando o método hand-out (75/25), construir modelos de regressão com os seguintes algoritmos: SVM Linear, SVM polinomial, kNN e Random Forest. </br>
b) Calcular o RMSE para os modelos. </br>
c) Apresentar um gráfico que mostre as curvas com os resultados das previsões e os dados originais (considerar só a base de testes). </br>
d) No gráfico, apresentar o RMSE de cada modelo na legenda. </br>

In [ ]:
import pandas as pd
import numpy as np

url = "https://drive.google.com/uc?id=18vLjeLLpKyFdFHAVODoEqhIrZxH9mK7O"

# carregar o dataset
df = pd.read_csv(url, names = ["Simbologia","Desavalorização","Fabricante","Combustível","Aspiração",
                               "Número de portas","Estilo","Tração","Localização do Motor","Base da roda",
                               "Comprimento","Largura","Altura","Peso","Tipo do motor","Quantidade de Cilindros",
                               "Tamanho do Motor","Sistema de Combustível","Calibre do Motor","Volume",
                               "Taxa de Compressão","Cavalos","Pico de RPM","Consumo na cidade","Consumo na rodovia",
                               "Valor"], header=None)


df = df.iloc[:, 2:]
df_ = df.loc[df["Valor"]=="?"]
df = df.drop(df_.index)
df["Valor"] = df["Valor"].astype(float)
df.head()

    Fabricante Combustível  ... Consumo na rodovia    Valor
0  alfa-romero         gas  ...                 27  13495.0
1  alfa-romero         gas  ...                 27  16500.0
2  alfa-romero         gas  ...                 26  16500.0
3         audi         gas  ...                 30  13950.0
4         audi         gas  ...                 22  17450.0

[5 rows x 24 columns]

In [ ]:
df.describe()

       Base da roda  Comprimento  ...  Consumo na rodovia         Valor
count    201.000000   201.000000  ...          201.000000    201.000000
mean      98.797015   174.200995  ...           30.686567  13207.129353
std        6.066366    12.322175  ...            6.815150   7947.066342
min       86.600000   141.100000  ...           16.000000   5118.000000
25%       94.500000   166.800000  ...           25.000000   7775.000000
50%       97.000000   173.200000  ...           30.000000  10295.000000
75%      102.400000   183.500000  ...           34.000000  16500.000000
max      120.900000   208.100000  ...           54.000000  45400.000000

[8 rows x 10 columns]